server:
  port: 8080
spring:
  application:
    name: roomba
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: ${DATASOURCE.URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml